name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: CI compilation test
    runs-on: ubuntu-latest

    steps:
      - name: 1 - Code checkout
        uses: actions/checkout@v3

      - name: 2 - Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: 3 - compile step
        run: mvn -B clean compile --file pom.xml

  test:
    name: CI lancement des Tests Unitaires
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: 1 - Code checkout
        uses: actions/checkout@v3

      - name: 2 - Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: 3 - Unit Test run
        run: mvn -B test --file pom.xml
